# Generated by Django 5.2.1 on 2025-06-02 12:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_categorie_article_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='nombre_vues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='VueArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('date_vue', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vues', to='blog.article')),
            ],
            options={
                'ordering': ['-date_vue'],
                'unique_together': {('article', 'adresse_ip', 'date_vue')},
            },
        ),
    ]
