# Generated by Django 5.2.1 on 2025-06-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_nombre_vues_vuearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text="Image d'illustration pour l'article", null=True, upload_to='articles/'),
        ),
    ]
