# Generated by Django 5.2.1 on 2025-06-02 14:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_tag_article_slug_article_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='est_publie',
            field=models.BooleanField(default=True, help_text='Article visible publiquement'),
        ),
        migrations.AddField(
            model_name='article',
            name='user_auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='est_approuve',
            field=models.BooleanField(default=True, help_text='Commentaire approuvé par la modération'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='user_auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lecteur', 'Lecteur'), ('auteur', 'Auteur'), ('moderateur', 'Modérateur'), ('admin', 'Administrateur')], default='lecteur', max_length=20)),
                ('bio', models.TextField(blank=True, help_text="Biographie de l'utilisateur", max_length=500)),
                ('avatar', models.ImageField(blank=True, help_text='Photo de profil', null=True, upload_to='avatars/')),
                ('site_web', models.URLField(blank=True, help_text='Site web personnel')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
