# Generated by Django 5.2.1 on 2025-06-04 10:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_est_publie_article_user_auteur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['nom'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='commentaire',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Commentaire', 'verbose_name_plural': 'Commentaires'},
        ),
        migrations.AlterModelOptions(
            name='profil',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Profil', 'verbose_name_plural': 'Profils'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['nom'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='vuearticle',
            options={'ordering': ['-date_vue'], 'verbose_name': "Vue d'article", 'verbose_name_plural': "Vues d'articles"},
        ),
        migrations.AlterField(
            model_name='article',
            name='auteur',
            field=models.CharField(max_length=100, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.categorie', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='article',
            name='est_publie',
            field=models.BooleanField(default=True, help_text='Article visible publiquement', verbose_name='Est publié'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text="Image d'illustration pour l'article", null=True, upload_to='articles/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='nombre_vues',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de vues'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='blog.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='article',
            name='titre',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user_auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur auteur'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='couleur',
            field=models.CharField(default='#007bff', help_text='Couleur en format hexadécimal (ex: #007bff)', max_length=7, verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='blog.article', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='contenu',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='est_approuve',
            field=models.BooleanField(default=True, help_text='Commentaire approuvé par la modération', verbose_name='Est approuvé'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='nom_auteur',
            field=models.CharField(max_length=100, verbose_name="Nom de l'auteur"),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='user_auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur auteur'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Photo de profil', null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='bio',
            field=models.TextField(blank=True, help_text="Biographie de l'utilisateur", max_length=500, verbose_name='Biographie'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='derniere_connexion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='role',
            field=models.CharField(choices=[('utilisateur', 'Utilisateur'), ('administrateur', 'Administrateur')], default='utilisateur', max_length=20, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='site_web',
            field=models.URLField(blank=True, help_text='Site web personnel', verbose_name='Site web'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='couleur',
            field=models.CharField(default='#6b7280', help_text='Couleur en format hexadécimal (ex: #6b7280)', max_length=7, verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='nom',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='vuearticle',
            name='adresse_ip',
            field=models.GenericIPAddressField(verbose_name='Adresse IP'),
        ),
        migrations.AlterField(
            model_name='vuearticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vues', to='blog.article', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='vuearticle',
            name='date_vue',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de vue'),
        ),
        migrations.AlterField(
            model_name='vuearticle',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('note_personnelle', models.TextField(blank=True, help_text='Note personnelle sur cet article', max_length=500, verbose_name='Note personnelle')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='blog.article', verbose_name='Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'ordering': ['-date_creation'],
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.article', verbose_name='Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'ordering': ['-date_creation'],
                'unique_together': {('user', 'article')},
            },
        ),
    ]
