# Generated by Django 5.2.1 on 2025-06-04 12:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_article_options_alter_categorie_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeCommentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_commentaire', to='blog.commentaire', verbose_name='Commentaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_commentaires', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Like de commentaire',
                'verbose_name_plural': 'Likes de commentaires',
                'ordering': ['-date_creation'],
                'unique_together': {('user', 'commentaire')},
            },
        ),
    ]
