# Generated by Django 5.2.1 on 2025-06-04 12:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_likecommentaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalementCommentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('spam', 'Spam'), ('harcelement', 'Harcèlement'), ('contenu_inapproprie', 'Contenu inapproprié'), ('fausses_informations', 'Fausses informations'), ('autre', 'Autre')], max_length=50, verbose_name='Motif')),
                ('description', models.TextField(blank=True, help_text='Description détaillée du problème (optionnel)', max_length=500, verbose_name='Description')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traite', 'Traité'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de signalement')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='blog.commentaire', verbose_name='Commentaire signalé')),
                ('moderateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_traites', to=settings.AUTH_USER_MODEL, verbose_name='Modérateur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur signalant')),
            ],
            options={
                'verbose_name': 'Signalement de commentaire',
                'verbose_name_plural': 'Signalements de commentaires',
                'ordering': ['-date_creation'],
                'unique_together': {('user', 'commentaire')},
            },
        ),
    ]
